//
// Generated file, do not edit! Created by nedtool 5.4 from inet/physicallayer/apskradio/bitlevel/APSKPhyFrame.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __INET__PHYSICALLAYER_APSKPHYFRAME_M_H
#define __INET__PHYSICALLAYER_APSKPHYFRAME_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0504
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef INET_API
#  if defined(INET_EXPORT)
#    define INET_API  OPP_DLLEXPORT
#  elif defined(INET_IMPORT)
#    define INET_API  OPP_DLLIMPORT
#  else
#    define INET_API
#  endif
#endif


namespace inet {
namespace physicallayer {

/**
 * Class generated from <tt>inet/physicallayer/apskradio/bitlevel/APSKPhyFrame.msg:21</tt> by nedtool.
 * <pre>
 * packet APSKPhyFrame
 * {
 * }
 * </pre>
 */
class INET_API APSKPhyFrame : public ::omnetpp::cPacket
{
  protected:

  private:
    void copy(const APSKPhyFrame& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const APSKPhyFrame&);

  public:
    APSKPhyFrame(const char *name=nullptr, short kind=0);
    APSKPhyFrame(const APSKPhyFrame& other);
    virtual ~APSKPhyFrame();
    APSKPhyFrame& operator=(const APSKPhyFrame& other);
    virtual APSKPhyFrame *dup() const override {return new APSKPhyFrame(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const APSKPhyFrame& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, APSKPhyFrame& obj) {obj.parsimUnpack(b);}

} // namespace physicallayer
} // namespace inet

#endif // ifndef __INET__PHYSICALLAYER_APSKPHYFRAME_M_H

