//
// Generated file, do not edit! Created by nedtool 5.4 from inet/physicallayer/ieee80211/bitlevel/Ieee80211PLCPFrame.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __INET__PHYSICALLAYER_IEEE80211PLCPFRAME_M_H
#define __INET__PHYSICALLAYER_IEEE80211PLCPFRAME_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0504
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef INET_API
#  if defined(INET_EXPORT)
#    define INET_API  OPP_DLLEXPORT
#  elif defined(INET_IMPORT)
#    define INET_API  OPP_DLLIMPORT
#  else
#    define INET_API
#  endif
#endif


namespace inet {
namespace physicallayer {

/**
 * Enum generated from <tt>inet/physicallayer/ieee80211/bitlevel/Ieee80211PLCPFrame.msg:21</tt> by nedtool.
 * <pre>
 * enum Ieee80211PLCPType
 * {
 *     OFDM = 0;
 *     DSSS = 1;
 *     Infrared = 2;
 *     FHSS = 3;
 *     HRDSSS = 4;
 *     ERP = 5;
 *     HT = 6;
 * }
 * </pre>
 */
enum Ieee80211PLCPType {
    OFDM = 0,
    DSSS = 1,
    Infrared = 2,
    FHSS = 3,
    HRDSSS = 4,
    ERP = 5,
    HT = 6
};

/**
 * Class generated from <tt>inet/physicallayer/ieee80211/bitlevel/Ieee80211PLCPFrame.msg:32</tt> by nedtool.
 * <pre>
 * packet Ieee80211PLCPFrame
 * {
 *     short type \@enum(Ieee80211PLCPType);
 * }
 * </pre>
 */
class INET_API Ieee80211PLCPFrame : public ::omnetpp::cPacket
{
  protected:
    short type;

  private:
    void copy(const Ieee80211PLCPFrame& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Ieee80211PLCPFrame&);

  public:
    Ieee80211PLCPFrame(const char *name=nullptr, short kind=0);
    Ieee80211PLCPFrame(const Ieee80211PLCPFrame& other);
    virtual ~Ieee80211PLCPFrame();
    Ieee80211PLCPFrame& operator=(const Ieee80211PLCPFrame& other);
    virtual Ieee80211PLCPFrame *dup() const override {return new Ieee80211PLCPFrame(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual short getType() const;
    virtual void setType(short type);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Ieee80211PLCPFrame& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Ieee80211PLCPFrame& obj) {obj.parsimUnpack(b);}

} // namespace physicallayer
} // namespace inet

#endif // ifndef __INET__PHYSICALLAYER_IEEE80211PLCPFRAME_M_H

